# this is a ready to use template if you want to deploy on google app engine
runtime: python310
entrypoint: python app.py

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

runtime_config:
  python_version: 3

env_variables:
  OPENAI_API_KEY: "key_goes_here"
  GOOGLE_APPLICATION_CREDENTIALS: "google_credentials_file_name_goes_here.json"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
